# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jenkins-material-theme
email: me@afonsof.com
description: Beautify your Jenkins with the Material Design theme!
baseurl: ""
url: "http://afonsof.github.io"
twitter_username: afonsof
github_username:  afonsof
github_url: "https://github.com/afonsof/jenkins-material-theme"

# Build settings
markdown: kramdown
